### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by bobfacer** [thua919/FMapping#1]
Hi! It's so exciting to see your work, I would like to know when the code will be released,Thanks!

**Comment by thua919** [comment]
Hi, Thanks for your attention! We plan to release the code upon receiving the review feedback and thus be able to make minor revisions.

Kind regards,
Tongyan
________________________________
From: bobfacer ***@***.***>
Sent: Monday, June 26, 2023 9:52 PM
To: thua919/FMapping ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thua919/FMapping] Code Release (Issue #1)


Hi! It's so exciting to see your work, I would like to know when the code will be released,Thanks!
